### ISSUE TITLE
Importing/Exporing data

### ISSUE THREAD

**Issue by finnziehe** [pmiddend/piggybudget#3]
Is there a way to export or backup the data?

**Comment by pmiddend** [comment]
Not yet, unfortunately. Do you have a proposition for that? Maybe just storing the history as a CSV file on the phone's drive would suffice.

**Comment by Zegnat** [comment]
Wondering if there is some clever way to use a [Plain Text Accounting](https://plaintextaccounting.org/) format like [hledger’s journal format](http://hledger.org/journal.html). This will give you plain text files that should be pretty easy to take away, that are also readable in any text editor (and still make sense), and they can be imported by several other open-source finance tools.

**Comment by pmiddend** [comment]
@Zegnat Funny that you mention it, because I've thought of exactly that myself. It would be pretty easy to implement. I personally use beancount as my plain text accounting tool, but both formats are pretty simple to export.
I'll try implementing it, after I implement the obligatory (and in this case appropriate) CSV export/import.
