### ISSUE TITLE
editable categories

### ISSUE THREAD

**Issue by paulle** [pmiddend/piggybudget#5]
First thanks for piggybudget.
It could be nice to have editable categories, it's difficult to have an icon for every possible category so pure text for editable categories should be sufficient.

**Comment by pmiddend** [comment]
A good suggestion. Most of the app is designed for to use symbols, though. Think about the pie chart or the history - those would need to be carefully redesigned so text won't destroy the layout.
So, when I get around to implementing this, I think I'll try to still use symbols. There's a _lot_ of those available, see (https://react-native-training.github.io/react-native-elements/docs/icon.html)[here], so I hope you find an icon (and color) for every category of your liking.

**Comment by paulle** [comment]
Thank you for the link to the icons. And yes you are right the app is designed for to use symbols and the nice pie chart depends of it too. What do you think (i don't if it's possible or too much work (I don't have any programming skills)) to put a line for a note when one is entering an income or expense and this note should only show up in the history?
Please excuse my ignorance but how can I change some icons, I found no option for doing it.

**Comment by pmiddend** [comment]
@paulle Regarding the "note" you can attach to a transaction: Your suggestion makes sense, and is pretty easy to implement, so I'll look into it. However, somebody else also asked for editable categories and I still think it's a good idea.
The thing is: I don't really want a whole interface for adding, editing and removing categories. For example, implementing such an interface would mean you'd have to think about what happens if you _remove_ a category that you already had transactions for. Should those disappear? Should the user be asked first? It's a bit to think about.
So what I cam up with is this: You have a fixed number of categories, as it is now. However, in the "Settings", you can edit these categories, assigning new colors and icons (this is, by the way, not possible currently, sorry that you were looking in vain). This way, deletion and insertion of categories isn't possible, but "reassigning" is.

**Comment by paulle** [comment]
@pmiddend the possibility of "reassigning" the fixed number of categories together with the possibility to attach a note to every transaction would be very fine and sufficient to adapt piggybudget more to one's personal preferences and the "note" option would one give more control to see where the goes.

**Comment by pmiddend** [comment]
I've created #7 and #8 to be a bit more organized about all this editing. :)
